### ISSUE TITLE
Can't crawl a site protected with basic http auth

### ISSUE THREAD

**Issue by changuelsami** [filiph/linkcheck#87] opened 2021-10-20 18:56 UTC
Hi,

My website is protected with a basic http authentification, so when I run this : 
./linkcheck https://foo:bar@mysite.tld
I get this error message : 
`INTERNAL ERROR: Sorry! Please open https://github.com/filiph/linkcheck/issues/new in your favorite browser and copy paste the following output there:

FormatException: Invalid radix-10 number (at character 1)
bar@mysite.tld
^

#0      int._throwFormatException (dart:core-patch/integers_patch.dart:132)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:143)
#2      int._parse (dart:core-patch/integers_patch.dart:101)
#3      int.parse (dart:core-patch/integers_patch.dart:64)
#4      new ServerInfo (package:linkcheck/src/server_info.dart:47)
#5      crawl.<anonymous closure> (package:linkcheck/src/crawl.dart:82)
#6      SetMixin.forEach (dart:collection/set.dart:142)
#7      crawl (package:linkcheck/src/crawl.dart:81)
#8      run (package:linkcheck/linkcheck.dart:280)
#9      main.<anonymous closure> (file:///home/runner/work/linkcheck/linkcheck/bin/linkcheck.dart:11)
#10     main.<anonymous closure> (file:///home/runner/work/linkcheck/linkcheck/bin/linkcheck.dart:9)
#11     _rootRun (dart:async/zone.dart:1354)
#12     _CustomZone.run (dart:async/zone.dart:1258)
#13     _runZoned (dart:async/zone.dart:1789)
#14     runZonedGuarded (dart:async/zone.dart:1777)
#15     main (file:///home/runner/work/linkcheck/linkcheck/bin/linkcheck.dart:9)
#16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
`

**Comment by tennox** [comment] 2021-12-01 17:27
Duplicate of https://github.com/filiph/linkcheck/issues/53
/close

**Closed** 2021-12-06 10:56 UTC
